import React from 'react';
import Swal from 'sweetalert2';
import {
    Sparkles,
    Loader2,
    CheckCircle2,
    AlertCircle,
    Settings,
    Eye,
    Pencil,
    Trash2,
    Save,
    Send,
    ChevronDown,
    X,
    Plus,
} from 'lucide-react';
import {
    AdminPageShell,
    AdminPageHeader,
    AdminPrimaryButton,
    AdminSecondaryButton,
    AdminContentCard,
    adminSelectClass,
    adminCompactInputClass,
} from '../components/admin/AdminLayout';
import { AdminDataTable, AdminTableActionButton } from '../components/admin/AdminDataTable';
import {
    LessonQuizQuestionBankReview,
    confirmUnsavedQuestionBankChanges,
} from './LessonQuizQuestionBankReview';
import {
    AI_SCENARIO_DEFAULT_LANGUAGE,
    resolveLearningObjectives,
    resolveScenarioDescription,
    resolveScenarioTitle,
} from '../utils/aiScenarioLocale';
import { showPortalToast } from '../utils/portalToast';

const BANK_COUNTS = [10, 20, 30];
const DEFAULT_BANK_COUNT = 20;

const BANK_COUNT_LABELS = {
    10: '10',
    20: '20 (Recommended)',
    30: '30 (Maximum)',
};

function recommendedQuizSizeForBank(bankCount) {
    const normalized = normalizeBankCount(bankCount);
    if (normalized === 10) return 5;
    if (normalized === 20) return 10;
    if (normalized === 30) return 15;

    return 10;
}

function buildParticipantQuizSizeOptions(poolSize) {
    const options = [];
    for (let size = 5; size <= poolSize; size += 5) {
        options.push(size);
    }
    return options;
}

function normalizeBankCount(count) {
    const parsed = Number(count);
    if (BANK_COUNTS.includes(parsed)) {
        return parsed;
    }

    if (parsed > 30) {
        return 30;
    }

    return DEFAULT_BANK_COUNT;
}

function normalizeQuizSize(count, bankCount) {
    const normalizedBank = normalizeBankCount(bankCount);
    const options = buildParticipantQuizSizeOptions(normalizedBank);
    const parsed = Number(count);

    if (options.includes(parsed)) {
        return parsed;
    }

    return recommendedQuizSizeForBank(normalizedBank);
}

const GENERATION_LANGUAGES = [
    { value: 'en', label: 'English' },
    { value: 'fil', label: 'Filipino' },
];

function formatDate(value) {
    if (!value) return '—';
    return new Date(value).toLocaleString();
}

function formatGeneratedDateParts(value) {
    if (!value) {
        return { date: '—', time: null };
    }

    const parsed = new Date(value);
    return {
        date: parsed.toLocaleDateString(undefined, { month: 'long', day: 'numeric', year: 'numeric' }),
        time: parsed.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit', second: '2-digit' }),
    };
}

function GeneratedDateCell({ value }) {
    const { date, time } = formatGeneratedDateParts(value);

    return (
        <div className="text-slate-600 text-xs leading-tight whitespace-nowrap">
            <div>{date}</div>
            {time && <div className="text-slate-500">{time}</div>}
        </div>
    );
}

function formatUserName(user, fallbackName) {
    if (fallbackName) return fallbackName;
    if (!user) return '—';
    return user.name || user.email || '—';
}

function formatDifficulty(value) {
    if (!value) return '—';
    return value.charAt(0).toUpperCase() + value.slice(1);
}

function displayAssessmentStatus(status) {
    if (status === 'published') return 'Published';
    if (status === 'archived') return 'Archived';
    return 'Draft';
}

function AssessmentStatusBadge({ status }) {
    const label = displayAssessmentStatus(status);
    const styles = {
        Published: 'bg-emerald-50 text-emerald-700 border-emerald-200',
        Draft: 'bg-amber-50 text-amber-700 border-amber-200',
        Archived: 'bg-slate-50 text-slate-600 border-slate-200',
    };

    return (
        <span className={`inline-flex items-center rounded-lg border px-2.5 py-0.5 text-xs font-medium ${styles[label] || styles.Draft}`}>
            {label}
        </span>
    );
}

function CurrentVersionBadge({ compact = false }) {
    return (
        <span className={`inline-flex items-center gap-1 rounded-lg border border-sky-200 bg-sky-50 font-medium text-sky-700 shrink-0 ${compact ? 'px-2 py-0.5 text-[0.65rem]' : 'px-2.5 py-0.5 text-xs'}`}>
            <CheckCircle2 className={compact ? 'w-3 h-3' : 'w-3.5 h-3.5'} />
            Current
        </span>
    );
}

function VersionAuditPanel({ version }) {
    const generatedBy = formatUserName(version.creator, version.generated_by_name);
    const publishedBy = formatUserName(version.publisher, version.published_by_name);
    const lastEditedBy = formatUserName(version.last_editor, version.last_edited_by_name);
    const isCurrent = version.is_current === true;

    const fields = [
        { label: 'Version', value: `v${version.version_number}` },
        { label: 'Generated By', value: generatedBy },
        { label: 'Generated On', value: formatDate(version.created_at) },
        { label: 'Published By', value: publishedBy },
        { label: 'Published On', value: formatDate(version.published_at) },
        { label: 'Status', value: <AssessmentStatusBadge status={version.status} /> },
        { label: 'Current Version', value: isCurrent ? 'Yes' : 'No' },
    ];

    if (version.last_edited_at) {
        fields.push(
            { label: 'Last Edited By', value: lastEditedBy },
            { label: 'Last Edited On', value: formatDate(version.last_edited_at) },
        );
    }

    return (
        <div className="rounded-xl border border-slate-200 bg-slate-50 p-4 mb-6">
            <h4 className="text-sm font-semibold text-slate-800 mb-3">Version Information</h4>
            <dl className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-3 text-sm">
                {fields.map((field) => (
                    <div key={field.label}>
                        <dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{field.label}</dt>
                        <dd className="mt-0.5 text-slate-800">{field.value}</dd>
                    </div>
                ))}
            </dl>
        </div>
    );
}

function ScenarioReadOnlyPanel({ version }) {
    const titleEn = resolveScenarioTitle(version, 'en');
    const titleFil = resolveScenarioTitle(version, 'fil');
    const descriptionEn = resolveScenarioDescription(version, 'en');
    const descriptionFil = resolveScenarioDescription(version, 'fil');
    const objectivesEn = resolveLearningObjectives(version, 'en');
    const objectivesFil = resolveLearningObjectives(version, 'fil');

    return (
        <div className="rounded-lg border border-slate-200 bg-white p-4 space-y-4 mb-6">
            <h4 className="text-sm font-semibold text-slate-800">Scenario Content</h4>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <div className="space-y-3">
                    <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">English</p>
                    <h5 className="text-base font-semibold text-slate-900">{titleEn}</h5>
                    <p className="text-sm text-slate-700 whitespace-pre-line">{descriptionEn}</p>
                    {objectivesEn && (
                        <ul className="list-disc list-inside text-sm text-slate-600">
                            {objectivesEn.split('\n').filter(Boolean).map((item) => (
                                <li key={`en-${item}`}>{item}</li>
                            ))}
                        </ul>
                    )}
                </div>
                <div className="space-y-3 lg:border-l lg:border-slate-100 lg:pl-6">
                    <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Filipino</p>
                    <h5 className="text-base font-semibold text-slate-900">{titleFil}</h5>
                    <p className="text-sm text-slate-700 whitespace-pre-line">{descriptionFil}</p>
                    {objectivesFil && (
                        <ul className="list-disc list-inside text-sm text-slate-600">
                            {objectivesFil.split('\n').filter(Boolean).map((item) => (
                                <li key={`fil-${item}`}>{item}</li>
                            ))}
                        </ul>
                    )}
                </div>
            </div>
            {version.disaster_type && (
                <p className="text-xs text-slate-500 pt-2 border-t border-slate-100">
                    Disaster type: <span className="font-medium text-slate-700">{version.disaster_type}</span>
                    {version.difficulty && (
                        <> · Difficulty: <span className="capitalize font-medium">{version.difficulty}</span></>
                    )}
                </p>
            )}
        </div>
    );
}

function ScenarioEditorSection({
    version,
    scenarioDraft,
    onScenarioDraftChange,
    onSaveScenario,
    onAddQuestion,
    workflowBusy,
}) {
    if (!scenarioDraft) return null;

    return (
        <div className="space-y-4 mb-6">
            <h4 className="text-sm font-semibold text-slate-800">Edit Scenario</h4>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                <div className="space-y-3">
                    <div>
                        <label className="block text-xs font-semibold text-slate-600 mb-1">Title (English)</label>
                        <input className={adminCompactInputClass} value={scenarioDraft.title_en} onChange={(e) => onScenarioDraftChange({ ...scenarioDraft, title_en: e.target.value })} />
                    </div>
                    <div>
                        <label className="block text-xs font-semibold text-slate-600 mb-1">Title (Filipino)</label>
                        <input className={adminCompactInputClass} value={scenarioDraft.title_fil} onChange={(e) => onScenarioDraftChange({ ...scenarioDraft, title_fil: e.target.value })} />
                    </div>
                    <div>
                        <label className="block text-xs font-semibold text-slate-600 mb-1">Disaster Type</label>
                        <input className={adminCompactInputClass} value={scenarioDraft.disaster_type} onChange={(e) => onScenarioDraftChange({ ...scenarioDraft, disaster_type: e.target.value })} />
                    </div>
                    {version?.difficulty && (
                        <p className="text-xs text-slate-500">
                            AI-determined difficulty: <span className="capitalize font-medium">{version.difficulty}</span>
                        </p>
                    )}
                </div>
                <div className="space-y-3">
                    <div>
                        <label className="block text-xs font-semibold text-slate-600 mb-1">Description (English)</label>
                        <textarea rows={4} className={adminCompactInputClass} value={scenarioDraft.description_en} onChange={(e) => onScenarioDraftChange({ ...scenarioDraft, description_en: e.target.value })} />
                    </div>
                    <div>
                        <label className="block text-xs font-semibold text-slate-600 mb-1">Description (Filipino)</label>
                        <textarea rows={4} className={adminCompactInputClass} value={scenarioDraft.description_fil} onChange={(e) => onScenarioDraftChange({ ...scenarioDraft, description_fil: e.target.value })} />
                    </div>
                    <div>
                        <label className="block text-xs font-semibold text-slate-600 mb-1">Learning Objectives (English)</label>
                        <textarea rows={3} className={adminCompactInputClass} value={scenarioDraft.learning_objectives_en} onChange={(e) => onScenarioDraftChange({ ...scenarioDraft, learning_objectives_en: e.target.value })} />
                    </div>
                    <div>
                        <label className="block text-xs font-semibold text-slate-600 mb-1">Learning Objectives (Filipino)</label>
                        <textarea rows={3} className={adminCompactInputClass} value={scenarioDraft.learning_objectives_fil} onChange={(e) => onScenarioDraftChange({ ...scenarioDraft, learning_objectives_fil: e.target.value })} />
                    </div>
                </div>
            </div>
            <div className="flex flex-wrap gap-2">
                <AdminPrimaryButton type="button" onClick={onSaveScenario} disabled={workflowBusy}>
                    <Save className="w-4 h-4" /> Save Scenario
                </AdminPrimaryButton>
                <AdminPrimaryButton type="button" onClick={onAddQuestion} disabled={workflowBusy}>
                    <Plus className="w-4 h-4" /> Add Question
                </AdminPrimaryButton>
            </div>
        </div>
    );
}

function workflowUrl(configId, versionId, suffix = '') {
    return `/admin/ai-scenario-config/${configId}/versions/${versionId}${suffix}`;
}

function serializeConfigPayload(payload) {
    return JSON.stringify(payload);
}

function buildScenarioDraft(version) {
    return {
        title_en: version.title_en || '',
        title_fil: version.title_fil || '',
        description_en: version.description_en || '',
        description_fil: version.description_fil || '',
        learning_objectives_en: version.learning_objectives_en || '',
        learning_objectives_fil: version.learning_objectives_fil || '',
        disaster_type: version.disaster_type || '',
    };
}

export function AiScenarioTrainingModule({ modules = [], configs = [] }) {
    const csrf = document.head.querySelector('meta[name="csrf-token"]')?.content || '';

    const configByModuleId = React.useMemo(() => {
        const map = {};
        (configs || []).forEach((c) => {
            map[c.training_module_id] = c;
        });
        return map;
    }, [configs]);

    const [selectedModuleId, setSelectedModuleId] = React.useState(
        modules[0]?.id ? String(modules[0].id) : '',
    );
    const [localConfigs, setLocalConfigs] = React.useState(configs || []);
    const [configExpanded, setConfigExpanded] = React.useState(false);
    const [configSynced, setConfigSynced] = React.useState(false);
    const [savedPayloadKey, setSavedPayloadKey] = React.useState('');

    const [saving, setSaving] = React.useState(false);
    const [generating, setGenerating] = React.useState(false);
    const [workflowBusy, setWorkflowBusy] = React.useState(false);
    const [activeGenerationJob, setActiveGenerationJob] = React.useState(null);
    const [questionBankDirty, setQuestionBankDirty] = React.useState(false);

    const [activeVersion, setActiveVersion] = React.useState(null);
    const [panelMode, setPanelMode] = React.useState(null);
    const [scenarioDraft, setScenarioDraft] = React.useState(null);

    const deepLinkHandled = React.useRef(false);
    const versionDeepLinkHandled = React.useRef(false);

    const [bankQuestionCount, setBankQuestionCount] = React.useState(DEFAULT_BANK_COUNT);
    const [quizQuestionCount, setQuizQuestionCount] = React.useState(recommendedQuizSizeForBank(DEFAULT_BANK_COUNT));
    const [quizSizePoolNotice, setQuizSizePoolNotice] = React.useState('');
    const [generationLanguage, setGenerationLanguage] = React.useState(AI_SCENARIO_DEFAULT_LANGUAGE);
    const [timeLimitMinutes, setTimeLimitMinutes] = React.useState(60);
    const [maxAttempts, setMaxAttempts] = React.useState(3);
    const [passingScore, setPassingScore] = React.useState(75);
    const [failRetakePolicy, setFailRetakePolicy] = React.useState('require_lesson_review');
    const [autoSubmitOnExpire, setAutoSubmitOnExpire] = React.useState(true);
    const [shuffleQuestions, setShuffleQuestions] = React.useState(true);
    const [shuffleAnswerChoices, setShuffleAnswerChoices] = React.useState(true);

    const selectedConfig = localConfigs.find(
        (c) => String(c.training_module_id) === String(selectedModuleId),
    );
    const selectedModule = modules.find((m) => String(m.id) === String(selectedModuleId));

    const participantQuizSizeOptions = React.useMemo(
        () => buildParticipantQuizSizeOptions(bankQuestionCount),
        [bankQuestionCount],
    );

    const buildPayload = React.useCallback(() => ({
        training_module_id: Number(selectedModuleId),
        bank_question_count: bankQuestionCount,
        quiz_question_count: Number(quizQuestionCount),
        generation_language: generationLanguage,
        time_limit_minutes: Number(timeLimitMinutes) > 0 ? Number(timeLimitMinutes) : 60,
        max_attempts: maxAttempts,
        passing_score: passingScore,
        fail_retake_policy: failRetakePolicy,
        auto_submit_on_expire: autoSubmitOnExpire,
        shuffle_questions: shuffleQuestions,
        shuffle_answer_choices: shuffleAnswerChoices,
    }), [
        selectedModuleId, bankQuestionCount, quizQuestionCount, generationLanguage, timeLimitMinutes,
        maxAttempts, passingScore, failRetakePolicy, autoSubmitOnExpire,
        shuffleQuestions, shuffleAnswerChoices,
    ]);

    const handleBankQuestionCountChange = React.useCallback((nextBank) => {
        const normalizedBank = normalizeBankCount(nextBank);
        const previousQuiz = Number(quizQuestionCount);
        const recommended = recommendedQuizSizeForBank(normalizedBank);
        const exceeded = Number.isFinite(previousQuiz) && previousQuiz > normalizedBank;

        setBankQuestionCount(normalizedBank);
        setQuizQuestionCount(recommended);

        if (exceeded) {
            setQuizSizePoolNotice('The participant quiz size has been adjusted because it exceeded the available AI question pool.');
        } else {
            setQuizSizePoolNotice('');
        }
    }, [quizQuestionCount]);

    const hydrateConfigForm = React.useCallback((existing) => {
        if (existing) {
            const bankCount = normalizeBankCount(existing.bank_question_count || existing.number_of_questions || DEFAULT_BANK_COUNT);
            setBankQuestionCount(bankCount);
            setQuizQuestionCount(normalizeQuizSize(existing.quiz_question_count, bankCount));
            setQuizSizePoolNotice('');
            setGenerationLanguage(existing.generation_language || existing.generated_language || AI_SCENARIO_DEFAULT_LANGUAGE);
            setTimeLimitMinutes(existing.time_limit_minutes > 0 ? existing.time_limit_minutes : 60);
            setMaxAttempts(existing.max_attempts ?? 3);
            setPassingScore(existing.passing_score ?? 75);
            setFailRetakePolicy(existing.fail_retake_policy || 'require_lesson_review');
            setAutoSubmitOnExpire(existing.auto_submit_on_expire !== false);
            setShuffleQuestions(existing.shuffle_questions !== false);
            setShuffleAnswerChoices(existing.shuffle_answer_choices !== false);
        } else {
            setBankQuestionCount(DEFAULT_BANK_COUNT);
            setQuizQuestionCount(recommendedQuizSizeForBank(DEFAULT_BANK_COUNT));
            setQuizSizePoolNotice('');
            setGenerationLanguage(AI_SCENARIO_DEFAULT_LANGUAGE);
            setTimeLimitMinutes(60);
            setMaxAttempts(3);
            setPassingScore(75);
            setFailRetakePolicy('require_lesson_review');
            setAutoSubmitOnExpire(true);
            setShuffleQuestions(true);
            setShuffleAnswerChoices(true);
        }
    }, []);

    React.useEffect(() => {
        if (deepLinkHandled.current) return;

        const params = new URLSearchParams(window.location.search);
        const moduleId = params.get('module');

        if (!moduleId) return;

        if (modules.some((module) => String(module.id) === String(moduleId))) {
            setSelectedModuleId(String(moduleId));
        }

        deepLinkHandled.current = true;
    }, [modules]);

    React.useEffect(() => {
        if (versionDeepLinkHandled.current) return;

        const versionId = new URLSearchParams(window.location.search).get('version');
        if (!versionId || !selectedConfig) return;

        const version = (selectedConfig.versions || []).find((item) => String(item.id) === String(versionId));
        if (!version) return;

        setActiveVersion(version);
        setPanelMode('view');
        setQuestionBankDirty(false);
        versionDeepLinkHandled.current = true;
    }, [selectedConfig]);

    React.useEffect(() => {
        setActiveGenerationJob(selectedConfig?.latest_generation_job?.is_active
            ? selectedConfig.latest_generation_job
            : null);
    }, [selectedConfig?.id, selectedConfig?.latest_generation_job]);

    React.useEffect(() => {
        const existing = configByModuleId[Number(selectedModuleId)];
        hydrateConfigForm(existing);
        if (existing) {
            const payload = {
                training_module_id: Number(selectedModuleId),
                bank_question_count: normalizeBankCount(existing.bank_question_count || existing.number_of_questions || DEFAULT_BANK_COUNT),
                quiz_question_count: normalizeQuizSize(existing.quiz_question_count, existing.bank_question_count || existing.number_of_questions || DEFAULT_BANK_COUNT),
                generation_language: existing.generation_language || existing.generated_language || AI_SCENARIO_DEFAULT_LANGUAGE,
                time_limit_minutes: existing.time_limit_minutes > 0 ? existing.time_limit_minutes : 60,
                max_attempts: existing.max_attempts ?? 3,
                passing_score: existing.passing_score ?? 75,
                fail_retake_policy: existing.fail_retake_policy || 'require_lesson_review',
                auto_submit_on_expire: existing.auto_submit_on_expire !== false,
                shuffle_questions: existing.shuffle_questions !== false,
                shuffle_answer_choices: existing.shuffle_answer_choices !== false,
            };
            setSavedPayloadKey(serializeConfigPayload(payload));
            setConfigSynced(true);
        } else {
            setSavedPayloadKey('');
            setConfigSynced(false);
        }
    }, [selectedModuleId, configByModuleId, hydrateConfigForm]);

    React.useEffect(() => {
        const currentKey = serializeConfigPayload(buildPayload());
        setConfigSynced(Boolean(savedPayloadKey) && currentKey === savedPayloadKey);
    }, [buildPayload, savedPayloadKey]);

    const scenarioRows = React.useMemo(() => {
        if (!selectedModuleId) return [];

        const rows = [];
        localConfigs.forEach((config) => {
            if (String(config.training_module_id) !== String(selectedModuleId)) return;

            (config.versions || []).forEach((version) => {
                if (version.status === 'archived') return;
                rows.push({
                    ...version,
                    is_current: version.is_current === true
                        || String(config.published_version_id) === String(version.id),
                    configId: config.id,
                    trainingModuleId: config.training_module_id,
                    trainingModuleTitle: config.training_module?.title || '—',
                    config,
                });
            });
        });
        return rows.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
    }, [localConfigs, selectedModuleId]);

    const refreshConfig = (config) => {
        setLocalConfigs((prev) => {
            const others = prev.filter((c) => c.training_module_id !== config.training_module_id);
            return [...others, config];
        });
        if (config.latest_generation_job?.is_active) {
            setActiveGenerationJob(config.latest_generation_job);
        } else if (config.latest_generation_job) {
            setActiveGenerationJob((prev) => (
                prev && prev.ai_scenario_config_id === config.id ? config.latest_generation_job : prev
            ));
        }
    };

    const findVersionContext = (versionRow) => {
        const config = localConfigs.find((c) =>
            c.id === versionRow.configId
            || c.versions?.some((v) => v.id === versionRow.id),
        ) || versionRow.config;
        const version = config?.versions?.find((v) => v.id === versionRow.id) || versionRow;
        return { config, version };
    };

    const apiFetch = async (url, options = {}) => {
        const res = await fetch(url, {
            ...options,
            headers: {
                'Content-Type': 'application/json',
                'X-CSRF-TOKEN': csrf,
                Accept: 'application/json',
                ...(options.headers || {}),
            },
        });
        const data = await res.json().catch(() => ({}));
        if (!res.ok) {
            const errors = data.errors ? Object.values(data.errors).flat().join('\n') : '';
            throw new Error(errors || data.message || 'Request failed');
        }
        return data;
    };

    const handleSaveConfig = async (e) => {
        e?.preventDefault?.();
        if (!selectedModuleId) return;
        setSaving(true);
        try {
            const payload = buildPayload();
            const data = await apiFetch('/admin/ai-scenario-config', {
                method: 'POST',
                body: JSON.stringify(payload),
            });
            refreshConfig(data.config);
            setSavedPayloadKey(serializeConfigPayload(payload));
            setConfigSynced(true);
            Swal.fire({ icon: 'success', title: 'Saved', text: data.message, timer: 2000, showConfirmButton: false });
        } catch (err) {
            Swal.fire({ icon: 'error', title: 'Error', text: err.message });
        } finally {
            setSaving(false);
        }
    };

    const handleGenerate = async () => {
        if (!selectedConfig?.id || !configSynced || activeGenerationJob?.is_active) return;

        const result = await Swal.fire({
            title: 'Generate AI Scenario & Questions?',
            html: 'Gemini will determine difficulty from the training module and generate the assessment as a draft in the background.',
            icon: 'question',
            showCancelButton: true,
            confirmButtonText: 'Generate',
            confirmButtonColor: '#059669',
        });
        if (!result.isConfirmed) return;

        setGenerating(true);
        try {
            const data = await apiFetch(`/admin/ai-scenario-config/${selectedConfig.id}/generate`, { method: 'POST' });
            setActiveGenerationJob(data.generation_job);
            setConfigExpanded(false);
            showPortalToast({
                title: 'AI Scenario generation has started.',
                description: 'You may continue using the system while the AI processes your assessment.',
            });
        } catch (err) {
            Swal.fire({ icon: 'error', title: 'Generation failed', text: err.message });
        } finally {
            setGenerating(false);
        }
    };

    React.useEffect(() => {
        if (!activeGenerationJob?.id || !activeGenerationJob?.is_active) return undefined;

        let cancelled = false;

        const pollStatus = async () => {
            try {
                const data = await apiFetch(`/admin/ai-scenario-generation-jobs/${activeGenerationJob.id}`);
                if (cancelled) return;

                const job = data.generation_job;
                setActiveGenerationJob(job);

                if (data.config) {
                    refreshConfig(data.config);
                }

                if (job?.status === 'completed') {
                    setActiveGenerationJob(null);
                    window.dispatchEvent(new CustomEvent('portal-notifications-refresh'));
                    showPortalToast({
                        title: 'AI Scenario generation completed.',
                        description: 'Review the new draft assessment when you are ready.',
                    });
                }

                if (job?.status === 'failed') {
                    setActiveGenerationJob(null);
                    window.dispatchEvent(new CustomEvent('portal-notifications-refresh'));
                }
            } catch {
                // keep polling on transient errors
            }
        };

        pollStatus();
        const timer = window.setInterval(pollStatus, 5000);
        return () => {
            cancelled = true;
            window.clearInterval(timer);
        };
    }, [activeGenerationJob?.id, activeGenerationJob?.is_active]);

    const runWorkflow = async (configId, versionId, suffix, { method = 'POST', body, successTitle, successText } = {}) => {
        if (!configId || !versionId) return null;
        setWorkflowBusy(true);
        try {
            const data = await apiFetch(workflowUrl(configId, versionId, suffix), {
                method,
                body: body ? JSON.stringify(body) : undefined,
            });
            if (data.config) {
                refreshConfig(data.config);
            }
            if (successTitle) {
                Swal.fire({ icon: 'success', title: successTitle, text: successText || data.message, timer: 2500, showConfirmButton: false });
            }
            return data;
        } catch (err) {
            Swal.fire({ icon: 'error', title: 'Action failed', text: err.message });
            return null;
        } finally {
            setWorkflowBusy(false);
        }
    };

    const openViewPanel = (row) => {
        const { version } = findVersionContext(row);
        setActiveVersion(version);
        setPanelMode('view');
        setQuestionBankDirty(false);
    };

    const openEditPanel = (row) => {
        const { version } = findVersionContext(row);
        setActiveVersion(version);
        setScenarioDraft(buildScenarioDraft(version));
        setPanelMode('edit');
        setQuestionBankDirty(false);
    };

    const closePanel = () => {
        if (!confirmUnsavedQuestionBankChanges(questionBankDirty)) {
            return;
        }
        setPanelMode(null);
        setActiveVersion(null);
        setScenarioDraft(null);
        setQuestionBankDirty(false);
    };

    const handlePublish = async (row) => {
        if (questionBankDirty && !confirmUnsavedQuestionBankChanges(questionBankDirty)) {
            return;
        }

        const { config, version } = findVersionContext(row);
        if (!config?.id || !version?.id) return;

        const confirm = await Swal.fire({
            title: 'Publish assessment?',
            text: 'Participants will be able to access this assessment when the module is enabled.',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#059669',
        });
        if (!confirm.isConfirmed) return;

        const data = await runWorkflow(config.id, version.id, '/publish', { successTitle: 'Published' });
        if (data?.config) {
            closePanel();
        }
    };

    const handleDelete = async (row) => {
        const { config, version } = findVersionContext(row);
        if (!config?.id || !version?.id) return;

        const confirm = await Swal.fire({
            title: `Delete version ${version.version_number}?`,
            text: 'This draft assessment will be permanently removed.',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#dc2626',
        });
        if (!confirm.isConfirmed) return;

        const data = await runWorkflow(config.id, version.id, '', { method: 'DELETE', successTitle: 'Deleted' });
        if (data && panelMode && activeVersion?.id === version.id) {
            closePanel();
        }
    };

    const handleSaveScenario = async () => {
        if (!scenarioDraft || !activeVersion) return;
        const { config } = findVersionContext(activeVersion);
        const data = await runWorkflow(config.id, activeVersion.id, '/scenario', {
            method: 'PATCH',
            body: scenarioDraft,
            successTitle: 'Scenario saved',
        });
        if (data?.config) {
            const updated = data.config.versions?.find((v) => v.id === activeVersion.id);
            if (updated) {
                setActiveVersion(updated);
                setScenarioDraft(buildScenarioDraft(updated));
            }
        }
    };

    const handleAddQuestion = async () => {
        if (!activeVersion) return;
        const { config } = findVersionContext(activeVersion);

        const data = await runWorkflow(config.id, activeVersion.id, '/questions', {
            method: 'POST',
            body: {
                question_en: 'New scenario question',
                choice_a_en: 'Option A',
                choice_b_en: 'Option B',
                choice_c_en: 'Option C',
                choice_d_en: 'Option D',
                correct_answer: 'A',
                explanation_en: '',
                competency: 'knowledge',
            },
            successTitle: 'Question added',
        });
        if (data?.version) {
            setActiveVersion(data.version);
        }
    };

    const activeVersionEditable = activeVersion
        && activeVersion.status !== 'published'
        && activeVersion.status !== 'archived';

    const renderAssessmentReview = (version, { readOnly = false } = {}) => {
        const { config } = findVersionContext(version);
        if (!config?.id || !version?.id) return null;

        return (
            <LessonQuizQuestionBankReview
                version={version}
                lessonTitle={selectedModule?.title}
                quizQuestionCount={config.quiz_question_count || recommendedQuizSizeForBank(config.bank_question_count || DEFAULT_BANK_COUNT)}
                readOnly={readOnly}
                editable={!readOnly && activeVersionEditable}
                workflowBusy={workflowBusy}
                prependContent={readOnly ? (
                    <>
                        <VersionAuditPanel version={version} />
                        <ScenarioReadOnlyPanel version={version} />
                    </>
                ) : (
                    <ScenarioEditorSection
                        version={version}
                        scenarioDraft={scenarioDraft}
                        onScenarioDraftChange={setScenarioDraft}
                        onSaveScenario={handleSaveScenario}
                        onAddQuestion={handleAddQuestion}
                        workflowBusy={workflowBusy}
                    />
                )}
                workflowUrl={(suffix) => workflowUrl(config.id, version.id, suffix)}
                apiFetch={apiFetch}
                onDirtyChange={setQuestionBankDirty}
                onVersionUpdated={(updatedVersion, updatedConfig) => {
                    if (updatedConfig) {
                        refreshConfig(updatedConfig);
                    }
                    setActiveVersion(updatedVersion);
                    if (!readOnly) {
                        setScenarioDraft(buildScenarioDraft(updatedVersion));
                    }
                    setQuestionBankDirty(false);
                }}
            />
        );
    };

    const scenarioColumns = [
        {
            key: 'version_number',
            label: 'Version',
            render: (row) => <span className="font-medium text-slate-800">v{row.version_number}</span>,
        },
        {
            key: 'trainingModuleTitle',
            label: 'Training Module',
            className: 'max-w-xs whitespace-normal',
            render: (row) => <span className="text-slate-700">{row.trainingModuleTitle}</span>,
        },
        {
            key: 'difficulty',
            label: 'Difficulty',
            render: (row) => <span className="capitalize text-slate-600">{formatDifficulty(row.difficulty)}</span>,
        },
        {
            key: 'question_count',
            label: 'Questions',
            render: (row) => <span className="text-slate-700">{row.question_count ?? (row.generated_questions?.length || 0)}</span>,
        },
        {
            key: 'status',
            label: 'Status',
            render: (row) => <AssessmentStatusBadge status={row.status} />,
        },
        {
            key: 'created_at',
            label: 'Generated Date',
            className: 'whitespace-nowrap',
            render: (row) => <GeneratedDateCell value={row.created_at} />,
        },
    ];

    return (
        <AdminPageShell>
            <AdminPageHeader
                icon={Sparkles}
                title="Final AI Scenario Assessment"
                description="Configure, generate, review, edit, and publish the final scenario-based assessment after all lessons are completed."
                actions={(
                    <select
                        className={adminSelectClass}
                        value={selectedModuleId}
                        onChange={(e) => {
                            setSelectedModuleId(e.target.value);
                            closePanel();
                        }}
                    >
                        <option value="">Select module…</option>
                        {(modules || []).map((m) => <option key={m.id} value={m.id}>{m.title}</option>)}
                    </select>
                )}
            />

            <AdminContentCard className="overflow-hidden">
                <button
                    type="button"
                    onClick={() => setConfigExpanded((prev) => !prev)}
                    className="w-full flex items-center justify-between gap-3 px-4 py-3 text-left hover:bg-slate-50 transition-colors"
                >
                    <span className="inline-flex items-center gap-2 text-sm font-semibold text-slate-800">
                        <Settings className="w-4 h-4 text-emerald-600" />
                        Configuration
                        {selectedModule && (
                            <span className="font-normal text-slate-500">— {selectedModule.title}</span>
                        )}
                    </span>
                    <ChevronDown className={`w-5 h-5 text-slate-400 transition-transform ${configExpanded ? 'rotate-180' : ''}`} />
                </button>

                {configExpanded && (
                    <div className="px-4 pb-4 border-t border-slate-100">
                        <form onSubmit={handleSaveConfig} className="pt-4 space-y-4">
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                                <div>
                                    <label className="block text-xs font-semibold text-slate-600 mb-1">AI Questions to Generate</label>
                                    <select className={adminCompactInputClass} value={bankQuestionCount} onChange={(e) => handleBankQuestionCountChange(Number(e.target.value))}>
                                        {BANK_COUNTS.map((n) => <option key={n} value={n}>{BANK_COUNT_LABELS[n] || n}</option>)}
                                    </select>
                                    <p className="text-[0.7rem] text-slate-500 mt-1">
                                        Recommended: 20 questions. Maximum: 30 questions.
                                    </p>
                                </div>
                                <div>
                                    <label className="block text-xs font-semibold text-slate-600 mb-1">Participant Quiz Size</label>
                                    <select
                                        className={adminCompactInputClass}
                                        value={String(quizQuestionCount)}
                                        onChange={(e) => {
                                            setQuizQuestionCount(Number(e.target.value));
                                            setQuizSizePoolNotice('');
                                        }}
                                    >
                                        {participantQuizSizeOptions.map((n) => (
                                            <option key={n} value={n}>{n}</option>
                                        ))}
                                    </select>
                                    {quizSizePoolNotice && (
                                        <p className="text-xs text-slate-600 mt-1">{quizSizePoolNotice}</p>
                                    )}
                                </div>
                                <div>
                                    <label className="block text-xs font-semibold text-slate-600 mb-1">Generation Language</label>
                                    <select className={adminCompactInputClass} value={generationLanguage} onChange={(e) => setGenerationLanguage(e.target.value)}>
                                        {GENERATION_LANGUAGES.map((lang) => <option key={lang.value} value={lang.value}>{lang.label}</option>)}
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-xs font-semibold text-slate-600 mb-1">Time Limit (minutes)</label>
                                    <input
                                        type="text"
                                        inputMode="numeric"
                                        pattern="[0-9]*"
                                        className={adminCompactInputClass}
                                        value={timeLimitMinutes === '' || timeLimitMinutes === null ? '' : String(timeLimitMinutes)}
                                        onChange={(e) => {
                                            const raw = e.target.value.replace(/[^\d]/g, '');
                                            setTimeLimitMinutes(raw === '' ? '' : Number(raw));
                                        }}
                                        onBlur={() => {
                                            if (timeLimitMinutes === '' || timeLimitMinutes === null) {
                                                setTimeLimitMinutes(60);
                                                return;
                                            }
                                            const clamped = Math.min(480, Math.max(1, Number(timeLimitMinutes) || 60));
                                            setTimeLimitMinutes(clamped);
                                        }}
                                    />
                                    <p className="text-[0.7rem] text-slate-500 mt-1">1–480 minutes. Clear the field to type a new value.</p>
                                </div>
                                <div>
                                    <label className="block text-xs font-semibold text-slate-600 mb-1">Passing Score (%)</label>
                                    <input type="number" min={1} max={100} className={adminCompactInputClass} value={passingScore} onChange={(e) => setPassingScore(Number(e.target.value))} />
                                </div>
                                <div>
                                    <label className="block text-xs font-semibold text-slate-600 mb-1">Max Attempts</label>
                                    <input type="number" min={1} max={20} className={adminCompactInputClass} value={maxAttempts} onChange={(e) => setMaxAttempts(Number(e.target.value))} />
                                </div>
                                <div>
                                    <label className="block text-xs font-semibold text-slate-600 mb-1">Fail Retake Policy</label>
                                    <select className={adminCompactInputClass} value={failRetakePolicy} onChange={(e) => setFailRetakePolicy(e.target.value)}>
                                        <option value="require_lesson_review">Review all lessons (no quiz retake)</option>
                                        <option value="quiz_retake_only">Final assessment retake only</option>
                                    </select>
                                    <p className="text-[0.7rem] text-slate-500 mt-1">
                                        {failRetakePolicy === 'require_lesson_review'
                                            ? 'On fail, participant must re-open and review every lesson. Lesson quizzes stay passed — no quiz retake required.'
                                            : 'On fail, participant may retake the Final AI Scenario Assessment immediately when attempts remain.'}
                                    </p>
                                </div>
                            </div>

                            <div className="flex flex-wrap gap-4">
                                <label className="flex items-center gap-2 text-sm text-slate-700">
                                    <input type="checkbox" checked={shuffleQuestions} onChange={(e) => setShuffleQuestions(e.target.checked)} className="rounded border-slate-300 text-emerald-600" />
                                    Shuffle questions
                                </label>
                                <label className="flex items-center gap-2 text-sm text-slate-700">
                                    <input type="checkbox" checked={shuffleAnswerChoices} onChange={(e) => setShuffleAnswerChoices(e.target.checked)} className="rounded border-slate-300 text-emerald-600" />
                                    Shuffle answer choices
                                </label>
                                <label className="flex items-center gap-2 text-sm text-slate-700">
                                    <input type="checkbox" checked={autoSubmitOnExpire} onChange={(e) => setAutoSubmitOnExpire(e.target.checked)} className="rounded border-slate-300 text-emerald-600" />
                                    Auto-submit on expire
                                </label>
                            </div>

                            {selectedModule && (
                                <p className="text-xs text-slate-500">
                                    Assessment difficulty is determined automatically from the selected training module. Generation runs in the background so you can continue working.
                                </p>
                            )}

                            {activeGenerationJob?.is_active && (
                                <div className="rounded-xl border border-violet-200 bg-violet-50 px-4 py-3 text-sm text-violet-900 flex items-start gap-3">
                                    <Loader2 className="w-4 h-4 animate-spin mt-0.5 shrink-0" />
                                    <div>
                                        <p className="font-medium">AI generation in progress</p>
                                        <p className="text-violet-800/90 mt-1">
                                            {activeGenerationJob.status_label || 'Processing'}
                                        </p>
                                    </div>
                                </div>
                            )}

                            <div className="flex flex-wrap items-center gap-2 pt-2">
                                <AdminPrimaryButton type="submit" disabled={saving || !selectedModuleId}>
                                    {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
                                    Save Configuration
                                </AdminPrimaryButton>
                                <AdminPrimaryButton
                                    type="button"
                                    onClick={handleGenerate}
                                    disabled={generating || !configSynced || !selectedConfig?.id || activeGenerationJob?.is_active}
                                    className="bg-violet-600 hover:bg-violet-700"
                                >
                                    {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
                                    Generate AI Content
                                </AdminPrimaryButton>
                                {!configSynced && selectedModuleId && (
                                    <span className="text-xs text-amber-600 inline-flex items-center gap-1">
                                        <AlertCircle className="w-3.5 h-3.5" />
                                        Save configuration before generating
                                    </span>
                                )}
                            </div>
                        </form>
                    </div>
                )}
            </AdminContentCard>

            <div className="flex items-center justify-between gap-2">
                <h2 className="text-sm font-semibold text-slate-800">
                    Generated AI Scenarios
                    {selectedModule && (
                        <span className="font-normal text-slate-500"> — {selectedModule.title}</span>
                    )}
                </h2>
                {selectedConfig?.published_version && (
                    <span className="text-xs text-sky-700 inline-flex items-center gap-1">
                        <CheckCircle2 className="w-3.5 h-3.5" />
                        Learners use v{selectedConfig.published_version.version_number}
                    </span>
                )}
            </div>

            <AdminDataTable
                columns={scenarioColumns}
                data={scenarioRows}
                rowKey="id"
                minWidth="860px"
                emptyTitle="No generated scenarios"
                emptyDescription={selectedModule
                    ? `No AI assessments for "${selectedModule.title}" yet. Save configuration and generate content.`
                    : 'Select a training module to view its assessments.'}
                renderActions={(row) => (
                    <div className="flex justify-end items-center gap-1.5">
                        <AdminTableActionButton icon={Eye} title="View" variant="view" onClick={() => openViewPanel(row)} />
                        {row.status !== 'published' && (
                            <>
                                <AdminTableActionButton icon={Pencil} title="Edit" variant="edit" onClick={() => openEditPanel(row)} />
                                <AdminTableActionButton icon={Trash2} title="Delete" variant="danger" onClick={() => handleDelete(row)} disabled={workflowBusy} />
                                <AdminTableActionButton icon={Send} title="Publish" variant="edit" onClick={() => handlePublish(row)} disabled={workflowBusy} />
                            </>
                        )}
                        {row.is_current && <CurrentVersionBadge compact />}
                    </div>
                )}
            />

            {panelMode && activeVersion && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
                    <div className="bg-white rounded-xl shadow-xl w-full max-w-6xl max-h-[92vh] flex flex-col min-h-0">
                        <div className="flex items-center justify-between gap-3 px-5 py-4 border-b border-slate-200 shrink-0">
                            <div>
                                <h3 className="text-lg font-semibold text-slate-900">
                                    {panelMode === 'view' ? 'View Assessment' : 'Edit Assessment'}
                                </h3>
                                <p className="text-xs text-slate-500 flex flex-wrap items-center gap-1.5">
                                    Version {activeVersion.version_number}
                                    <AssessmentStatusBadge status={activeVersion.status} />
                                    {activeVersion.is_current && <CurrentVersionBadge />}
                                    {questionBankDirty && (
                                        <span className="inline-flex items-center gap-1 text-amber-700">
                                            <span className="h-1.5 w-1.5 rounded-full bg-amber-500" />
                                            Unsaved Changes
                                        </span>
                                    )}
                                </p>
                            </div>
                            <button type="button" onClick={closePanel} className="p-2 rounded-lg hover:bg-slate-100 text-slate-500">
                                <X className="w-5 h-5" />
                            </button>
                        </div>

                        <div className="flex flex-1 min-h-0 flex-col">
                            {renderAssessmentReview(activeVersion, { readOnly: panelMode === 'view' })}
                        </div>

                        {panelMode === 'edit' && activeVersionEditable && (
                            <div className="px-5 py-4 border-t border-slate-200 flex justify-end gap-2 shrink-0">
                                <AdminSecondaryButton onClick={closePanel}>Close</AdminSecondaryButton>
                                <AdminPrimaryButton onClick={() => handlePublish(activeVersion)} disabled={workflowBusy}>
                                    <Send className="w-4 h-4" /> Publish
                                </AdminPrimaryButton>
                            </div>
                        )}
                    </div>
                </div>
            )}
        </AdminPageShell>
    );
}
